STUDENT_NAME = "Yulian Mykhalchuk"
STUDENT_GROUP = "IT-32"

DB_FILE = "workspace_mykhalchuk.db"
APP_TITLE = "Notes Manager"

CASCADE_STEP = 40
DEFAULT_PREVIEW_LENGTH = 30
TABLE_PREVIEW_LENGTH = 40
LONG_NOTE_CHARS = 200
EMPTY_TABLE_TEXT = "No notes to show"
ORG_NAME = "KTBP"
LOG_FILE = "notes_manager.log"
LOG_MAX_BYTES = 1_000_000
LOG_BACKUP_COUNT = 3
RECENT_EXPORTS_MAX = 5